### ISSUE TITLE
Update static image to bit wilp

### ISSUE THREAD

**Issue by csreedevibits** [csreedevibits/Assignment4Osse#25]
@sesibomman
![bitswilp](https://user-images.githubusercontent.com/79320933/115044576-4530ce00-9ef3-11eb-9735-63f49cd644d5.png)
a

**Comment by sesibommana** [comment]
![BITS WILP](https://user-images.githubusercontent.com/79452242/115074130-e54c1e80-9f16-11eb-8327-310c0be65ff1.jpg)
